---
- name: Install lighthouse
  hosts: lighthouse-01
  become: true
  roles:
    - lighthouse-role

- name: Install Clickhouse
  hosts: clickhouse-01
  become: true
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector-01
  become: true
  roles:
    - vector-role
